---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ritrdasn/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp header.html $DEPLOYPATH
    - /bin/cp footer.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R d2 $DEPLOYPATH
    - /bin/cp -R d4 $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH